language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8
   
sudo: false # faster builds

script: "mvn cobertura:cobertura"

after_success:
- bash <(curl -s https://codecov.io/bash)